# Reference: https://docs.github.com/en/packages/guides/configuring-npm-for-use-with-github-packages#publishing-a-package
#
# * All packages are scoped to "@newscorp-ghfb", so make sure the package name in your package.json has the format: @newscorp-ghfb/<name or package>
# * Consider using Conventional Commits to auto increment the version
# * You may want to modify the branches to something like "release" if you're publishing "stable", production ready code.
# * From a continous integration standpoint, you can keep the default branch as the push target but then you may want to tag them as "pre-release".
#
# If you need to read other newscorp-ghfb packages, you need to
#   * create a personal access token and
#   * ensure it has read:packages scope and the user has read access to the repo.
#   https://docs.github.com/en/packages/learn-github-packages/about-github-packages#about-scopes-and-permissions-for-package-registries

name: Dow Jones CD workflow for Node JS apps

on:
  push:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          always-auth: true
          registry-url: https://npm.pkg.github.com
          scope: '@newscorp-ghfb'
      - run: npm ci
        # env:
          # NODE_AUTH_TOKEN: ${{secrets.PAT}}
      # replace this step with your own if needed
      - run: npm run build
      - run: npm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
